$( document ).ready(function() {

    $("#myth_01_box").mouseover(function(){
        $("#myth_01_box").addClass("myth-border-rollover");
        $("#myth_01_box").removeClass("myth-border");
        $("#myth_01_content").toggle();
        $("#myth_01_title").toggle();
    });
    $("#myth_01_box").mouseout(function(){
        $("#myth_01_box").removeClass("myth-border-rollover");
        $("#myth_01_box").addClass("myth-border");
        $("#myth_01_content").toggle();
        $("#myth_01_title").toggle();
    });

    $("#myth_02_box").mouseover(function(){
        $("#myth_02_box").addClass("myth-border-rollover");
        $("#myth_02_box").removeClass("myth-border");
        $("#myth_02_content").toggle();
        $("#myth_02_title").toggle();
    });
    $("#myth_02_box").mouseout(function(){
        $("#myth_02_box").removeClass("myth-border-rollover");
        $("#myth_02_box").addClass("myth-border");
        $("#myth_02_content").toggle();
        $("#myth_02_title").toggle();
    });

    $("#myth_03_box").mouseover(function(){
        $("#myth_03_box").addClass("myth-border-rollover");
        $("#myth_03_box").removeClass("myth-border");
        $("#myth_03_content").toggle();
        $("#myth_03_title").toggle();
    });
    $("#myth_03_box").mouseout(function(){
        $("#myth_03_box").removeClass("myth-border-rollover");
        $("#myth_03_box").addClass("myth-border");
        $("#myth_03_content").toggle();
        $("#myth_03_title").toggle();
    });

    $("#myth_04_box").mouseover(function(){
        $("#myth_04_box").addClass("myth-border-rollover");
        $("#myth_04_box").removeClass("myth-border");
        $("#myth_04_content").toggle();
        $("#myth_04_title").toggle();
    });
    $("#myth_04_box").mouseout(function(){
        $("#myth_04_box").removeClass("myth-border-rollover");
        $("#myth_04_box").addClass("myth-border");
        $("#myth_04_content").toggle();
        $("#myth_04_title").toggle();
    });

    $("#myth_05_box").mouseover(function(){
        $("#myth_05_box").addClass("myth-border-rollover");
        $("#myth_05_box").removeClass("myth-border");
        $("#myth_05_content").toggle();
        $("#myth_05_title").toggle();
    });
    $("#myth_05_box").mouseout(function(){
        $("#myth_05_box").removeClass("myth-border-rollover");
        $("#myth_05_box").addClass("myth-border");
        $("#myth_05_content").toggle();
        $("#myth_05_title").toggle();
    });

    $("#myth_06_box").mouseover(function(){
        $("#myth_06_box").addClass("myth-border-rollover");
        $("#myth_06_box").removeClass("myth-border");
        $("#myth_06_content").toggle();
        $("#myth_06_title").toggle();
    });
    $("#myth_06_box").mouseout(function(){
        $("#myth_06_box").removeClass("myth-border-rollover");
        $("#myth_06_box").addClass("myth-border");
        $("#myth_06_content").toggle();
        $("#myth_06_title").toggle();
    });

    $("#myth_07_box").mouseover(function(){
        $("#myth_07_box").addClass("myth-border-rollover");
        $("#myth_07_box").removeClass("myth-border");
        $("#myth_07_content").toggle();
        $("#myth_07_title").toggle();
    });
    $("#myth_07_box").mouseout(function(){
        $("#myth_07_box").removeClass("myth-border-rollover");
        $("#myth_07_box").addClass("myth-border");
        $("#myth_07_content").toggle();
        $("#myth_07_title").toggle();
    });

    $("#myth_08_box").mouseover(function(){
        $("#myth_08_box").addClass("myth-border-rollover");
        $("#myth_08_box").removeClass("myth-border");
        $("#myth_08_content").toggle();
        $("#myth_08_title").toggle();
    });
    $("#myth_08_box").mouseout(function(){
        $("#myth_08_box").removeClass("myth-border-rollover");
        $("#myth_08_box").addClass("myth-border");
        $("#myth_08_content").toggle();
        $("#myth_08_title").toggle();
    });

    $("#myth_09_box").mouseover(function(){
        $("#myth_09_box").addClass("myth-border-rollover");
        $("#myth_09_box").removeClass("myth-border");
        $("#myth_09_content").toggle();
        $("#myth_09_title").toggle();
    });
    $("#myth_09_box").mouseout(function(){
        $("#myth_09_box").removeClass("myth-border-rollover");
        $("#myth_09_box").addClass("myth-border");
        $("#myth_09_content").toggle();
        $("#myth_09_title").toggle();
    });

    $("#myth_10_box").mouseover(function(){
        $("#myth_10_box").addClass("myth-border-rollover");
        $("#myth_10_box").removeClass("myth-border");
        $("#myth_10_content").toggle();
        $("#myth_10_title").toggle();
    });
    $("#myth_10_box").mouseout(function(){
        $("#myth_10_box").removeClass("myth-border-rollover");
        $("#myth_10_box").addClass("myth-border");
        $("#myth_10_content").toggle();
        $("#myth_10_title").toggle();
    });
});